apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: app-svc
  labels:
    app: app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    name: nginx
    targetPort: 5000
    nodePort: 32000
  selector:
    run: webapp 
